### ISSUE TITLE
Bug: Missing package: com.infinityiterators.bookwms.account

### ISSUE THREAD

**Issue by kebin0591** [ssg-240304-java2/wms-InfinityIterators#48]
`CustomerLoginMenu.java` 파일을 컴파일하는 동안 다음과 같은 오류가 발생했습니다:
![image](https://github.com/ssg-240304-java2/wms-InfinityIterators/assets/166422645/4d169908-89fa-4d98-9b0e-92990f78ab6c)

`com.infinityiterators.bookwms.account` 패키지가 존재하지 않는 것 같습니다. 이 문제를 해결하기 위해 필요한 조치를 취해주시기 바랍니다.

**Comment by DokaDev** [comment]
해당사항 곧 PR로 반영합니다
